Docs: add architectural documentation
SanteonNL/orca pull request #46
Opened 2024-08-30 14:27 UTC by reinkrul

2024-09-04 17:06 UTC, JorisHeadease requested changes

2024-09-04 17:06 UTC, JorisHeadease commented on README.md
> +  The *Frontend* has a websocket connection to the *Task Engine* to receive updates on the Task status.
I think it's probably easier to use something like an `EventSource`  to stream data from the server to the client, we only need to receive data, and it's much easier to implement. 

```suggestion
  The *Frontend* is notified by the *Task Engine* when the Task status changes.
```

2024-09-04 17:06 UTC, JorisHeadease commented on docs/images/system-diagram.svg
Maybe we can also add the `Task Engine (TODO)` in the image as it's already described in the README

2024-09-05 07:49 UTC, reinkrul commented on docs/images/system-diagram.svg
Updates the diagram. I removed the "Task Engine", since (initially) it will be part of the Care Plan Contributor implementation in Orchestrator.

2024-09-05 08:31 UTC, dwelman approved these changes

2024-09-05 09:03 UTC, reinkrul commented
Merged to have it ready for meeting, additional feedback is still welcome.

2024-09-05 09:03 UTC, merged

2024-09-05 10:39 UTC, JorisHeadease commented
Looks good @reinkrul!